#!/usr/bin/env python3
"""Generates the adaptive launcher icon (foreground, background, monochrome).

Run from the repository root:  python3 tools/icon/gen_icon.py
Writes app/src/main/res/drawable/ic_launcher_*.xml and tools/icon/preview.html
(open it in a browser to see the icon under circle, squircle and themed masks).
"""
import math
import os

RES = os.path.join("app", "src", "main", "res", "drawable")
HERE = os.path.dirname(os.path.abspath(__file__))

def rr(x0,y0,x1,y1,r):
    return (f"M{x0+r:.2f},{y0:.2f}H{x1-r:.2f}A{r},{r} 0,0 1 {x1:.2f},{y0+r:.2f}V{y1-r:.2f}"
            f"A{r},{r} 0,0 1 {x1-r:.2f},{y1:.2f}H{x0+r:.2f}A{r},{r} 0,0 1 {x0:.2f},{y1-r:.2f}V{y0+r:.2f}"
            f"A{r},{r} 0,0 1 {x0+r:.2f},{y0:.2f}Z")

# --- seven segment glyphs -------------------------------------------------
W, H, T = 6.0, 11.0, 1.7   # digit width, height, stroke
def seg(x, y, name):
    # hexagon-ish segments with small gaps
    g = 0.35
    h = T/2
    if name in 'adg':
        yy = {'a': y + h, 'g': y + H/2, 'd': y + H - h}[name]
        x0, x1 = x + g + h, x + W - g - h
        return f"M{x0-h:.2f},{yy:.2f}L{x0:.2f},{yy-h:.2f}H{x1:.2f}L{x1+h:.2f},{yy:.2f}L{x1:.2f},{yy+h:.2f}H{x0:.2f}Z"
    xx = x + h if name in 'fe' else x + W - h
    if name in 'fb':
        y0, y1 = y + h + g, y + H/2 - g
    else:
        y0, y1 = y + H/2 + g, y + H - h - g
    return f"M{xx:.2f},{y0:.2f}L{xx+h:.2f},{y0+h:.2f}V{y1-h:.2f}L{xx:.2f},{y1:.2f}L{xx-h:.2f},{y1-h:.2f}V{y0+h:.2f}Z"
GLYPH = {'1': 'bc', '2': 'abged', 'C': 'afed', 'c': 'ged'}
def digits(text, right, top, gap=1.9):
    paths = []
    x = right - len(text) * W - (len(text) - 1) * gap
    for ch in text:
        paths += [seg(x, top, s) for s in GLYPH[ch]]
        x += W + gap
    return "".join(paths)

# --- layout inside the 66dp safe circle (centre 54,54, r 33) ---------------
L, R = 29.0, 79.0
disp = (L, 32.5, R, 50.0)
stripe = (L + 1, 52.6, R - 1, 53.9)
row1 = (56.3, 64.9)
row2 = (66.9, 75.5)
kw, gap = (R - L - 4 * 2.0) / 5, 2.0
cols = [(L + k * (kw + gap), L + k * (kw + gap) + kw) for k in range(5)]
for (x, y) in [(L, 75.5), (R, 75.5), (L, 32.5), (R, 32.5)]:
    d = math.hypot(x - 54, y - 54)
    assert d <= 33.6, (x, y, d)

display_glass = rr(*disp, 3.2)
display_inner = rr(disp[0] + 1.3, disp[1] + 1.3, disp[2] - 1.3, disp[3] - 1.3, 2.2)
text = digits('12C', right=disp[2] - 4.0, top=35.75, gap=2.0)
stripe_p = rr(*stripe, 0.65)
gray = [rr(cols[c][0], row1[0], cols[c][1], row1[1], 1.6) for c in range(4)]
gray += [rr(cols[c][0], row2[0], cols[c][1], row2[1], 1.6) for c in (2, 3)]
f_key = rr(cols[0][0], row2[0], cols[0][1], row2[1], 1.6)
g_key = rr(cols[1][0], row2[0], cols[1][1], row2[1], 1.6)
enter = rr(cols[4][0], row1[0], cols[4][1], row2[1], 1.6)
# a lighter top face on each key, like the 12c's sloped key tops
def cap(x0, y0, x1, y1):
    return rr(x0 + 0.9, y0 + 0.9, x1 - 0.9, y0 + (y1 - y0) * 0.58, 1.0)
caps = [cap(cols[c][0], row1[0], cols[c][1], row1[1]) for c in range(4)]
caps += [cap(cols[c][0], row2[0], cols[c][1], row2[1]) for c in (2, 3)]
caps.append(cap(cols[4][0], row1[0], cols[4][1], row1[0] + (row1[1] - row1[0])))

GREEN, GOLD, GOLD_HI, BLUE, BLUE_HI = "#FF39FF6A", "#FFE8A33D", "#FFFFCB6B", "#FF4FA3E0", "#FF8CCBFF"

fg = f'''<?xml version="1.0" encoding="utf-8"?>
<!--
  A pocket 12c: the phosphor display reading "12C" over the gold stripe and a
  2x5 keypad with the gold f, blue g and the tall ENTER. Everything sits inside
  the 66dp adaptive-icon safe zone. Generated by tools/icon/gen_icon.py: edit that, not this.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!-- Display bezel and glass -->
    <path android:fillColor="#FF2C2F31" android:pathData="{display_glass}" />
    <path android:pathData="{display_inner}">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="62" android:centerY="41" android:gradientRadius="30"
                android:startColor="#FF0E3A18" android:endColor="#FF031006" />
        </aapt:attr>
    </path>
    <!-- Phosphor glow, then the segments -->
    <path android:fillColor="#5539FF6A" android:strokeColor="#3339FF6A" android:strokeWidth="1.6" android:strokeLineJoin="round" android:pathData="{text}" />
    <path android:fillColor="{GREEN}" android:pathData="{text}" />
    <!-- Gold stripe -->
    <path android:fillColor="{GOLD}" android:pathData="{stripe_p}" />
    <!-- Keys -->
    <path android:fillColor="#FF2A2D30" android:pathData="{''.join(gray)}{enter}" />
    <path android:fillColor="#FF575C62" android:pathData="{''.join(caps)}" />
    <path android:fillColor="{GOLD}" android:pathData="{f_key}" />
    <path android:fillColor="{GOLD_HI}" android:pathData="{cap(cols[0][0], row2[0], cols[0][1], row2[1])}" />
    <path android:fillColor="{BLUE}" android:pathData="{g_key}" />
    <path android:fillColor="{BLUE_HI}" android:pathData="{cap(cols[1][0], row2[0], cols[1][1], row2[1])}" />
</vector>
'''
bg = '''<?xml version="1.0" encoding="utf-8"?>
<!-- The 12c's dark faceplate with a soft top-left sheen. Generated by tools/icon/gen_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="20" android:startY="0" android:endX="88" android:endY="108"
                android:startColor="#FF3A3D40" android:centerColor="#FF17191A" android:endColor="#FF0A0B0B" />
        </aapt:attr>
    </path>
</vector>
'''
# Monochrome: one tint. Display is a ring with the segments inside; keys are solid.
mono = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Themed-icon silhouette: display outline with "12C", the stripe and the keypad. Generated by tools/icon/gen_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="{display_glass}{display_inner}" />
    <path android:fillColor="#FFFFFFFF" android:pathData="{text}{stripe_p}{''.join(gray)}{enter}{f_key}{g_key}" />
</vector>
'''
open(os.path.join(RES, 'ic_launcher_foreground.xml'), 'w').write(fg)
open(os.path.join(RES, 'ic_launcher_background.xml'), 'w').write(bg)
open(os.path.join(RES, 'ic_launcher_monochrome.xml'), 'w').write(mono)

# SVG previews: full-bleed, circle mask, squircle mask, and themed mono.
def svg_body(mask):
    return f'''
  <defs>
    <linearGradient id="bg{abs(hash(mask))}" x1="20" y1="0" x2="88" y2="108" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#3A3D40"/><stop offset="0.5" stop-color="#17191A"/><stop offset="1" stop-color="#0A0B0B"/></linearGradient>
    <radialGradient id="glass{abs(hash(mask))}" cx="62" cy="41" r="30" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#0E3A18"/><stop offset="1" stop-color="#031006"/></radialGradient>
    <clipPath id="m{abs(hash(mask))}">{mask}</clipPath>
  </defs>
  <g clip-path="url(#m{abs(hash(mask))})">
    <rect width="108" height="108" fill="url(#bg{abs(hash(mask))})"/>
    <path fill="#2C2F31" d="{display_glass}"/>
    <path fill="url(#glass{abs(hash(mask))})" d="{display_inner}"/>
    <path fill="#39FF6A" fill-opacity="0.33" stroke="#39FF6A" stroke-opacity="0.2" stroke-width="1.6" stroke-linejoin="round" d="{text}"/>
    <path fill="#39FF6A" d="{text}"/>
    <path fill="#E8A33D" d="{stripe_p}"/>
    <path fill="#2A2D30" d="{''.join(gray)}{enter}"/>
    <path fill="#575C62" d="{''.join(caps)}"/>
    <path fill="#E8A33D" d="{f_key}"/><path fill="#FFCB6B" d="{cap(cols[0][0], row2[0], cols[0][1], row2[1])}"/>
    <path fill="#4FA3E0" d="{g_key}"/><path fill="#8CCBFF" d="{cap(cols[1][0], row2[0], cols[1][1], row2[1])}"/>
  </g>'''
masks = {
  'circle': '<circle cx="54" cy="54" r="36"/>',
  'squircle': '<rect x="18" y="18" width="72" height="72" rx="22"/>',
  'full': '<rect width="108" height="108"/>',
}
html = '<html><body style="background:#777;margin:0;padding:20px;display:flex;gap:24px;flex-wrap:wrap;align-items:center">'
for name, m in masks.items():
    html += f'<svg width="324" height="324" viewBox="0 0 108 108">{svg_body(m)}</svg>'
# small sizes
for px in (48, 72, 96):
    html += f'<svg width="{px}" height="{px}" viewBox="18 18 72 72">{svg_body(masks["circle"])}</svg>'
# mono on themed background
html += f'''<svg width="324" height="324" viewBox="0 0 108 108"><clipPath id="c2"><circle cx="54" cy="54" r="36"/></clipPath>
<g clip-path="url(#c2)"><rect width="108" height="108" fill="#DCE8C8"/>
<path fill="#2E3B1E" fill-rule="evenodd" d="{display_glass}{display_inner}"/>
<path fill="#2E3B1E" d="{text}{stripe_p}{''.join(gray)}{enter}{f_key}{g_key}"/></g></svg>'''
html += '</body></html>'
open(os.path.join(HERE, 'preview.html'), 'w').write(html)
print("wrote", RES)
